spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false


  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:47.106.170.7}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:lemon123}
    #连接超时时间
    timeout: 5000
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  #    - classpath*:me/**/mapper/*.xml



  #jwt:
  #  tokenHeader: Authorization #JWT存储的请求头
  #  secret: mySecret #JWT加解密使用的密钥
  #  expiration: 604800 #JWT的超期限时间(60*60*24)
  #  tokenHead: Bearer  #JWT负载中拿到开头



  #jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html  14400000
  token-validity-in-seconds: 600000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期 1800000
  detect: 120000
  # 续期时间范围，默认1小时，单位毫秒 3600000
  renew: 120000